# ====================== #
# ========公共配置======== #
# ====================== #

spring:
  application:
    name: cbrc-statement-verify-services
  profiles:
    active: dev
  mvc:
    converters:
      preferred-json-mapper: fastJson
  servlet:
    multipart:
      enabled: true
      max-file-size: 30MB
      max-request-size: 30MB
server:
  port: 1989


logging:
  file:
    name: d:\\logs\\crbic-statement-verify-services.log